language: node_js
node_js:
  - 10
cache:
  directories:
  - node_modules
script:
  - "npm i"
  - "npm run build"
deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

